apiVersion: apps/v1
kind: Deployment
metadata:
  name: agarioclone-service
  labels:
    app: agarioclone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agarioclone
  template:
    metadata:
      labels:
        app: agarioclone
    spec:
      containers:
        - name: "agarioclone-app"
          image: agarioclone_agar:v0
          ports:
            - containerPort: 8080