apiVersion: v1
kind: Service
metadata:
  name: agarioclone-service
spec:
  type: NodePort
  selector:
    app: agarioclone
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30090